language: generic
sudo: required
dist: trusty
os:
- linux
- osx
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
- make emake.mk
- make setup
install:
- make .elpa
script:
# test uncompiled
- make test-ert
- make test-buttercup
# test compilation
- make compile
# test compiled
- make test-ert
- make test-buttercup
# linting
- make lint-package-lint
- make lint-checkdoc
