language: generic
sudo: required
dist: trusty
os:
- linux
- osx
addons:
  homebrew:
    packages:
      - autoconf
      - automake
      - gnutls
      - texinfo
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  global:
  - EMAKE_SHA1=4a42b2d8a2fb775389a3e6092924c6a25173a81e
  - EMACS_INSTALL_DESTINATION=$HOME/emacs
  - EMACS=$HOME/emacs/bin/emacs
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
- wget "https://raw.githubusercontent.com/vermiculus/emake.el/${EMAKE_SHA1}/emake.mk"
- make setup
install:
- make install
script:
# test uncompiled
- make test-ert
- make test-buttercup
# test compilation
- make compile
# test compiled
- make test-ert
- make test-buttercup
# linting
- make lint-package-lint
- make lint-checkdoc
