language: generic
sudo: required
dist: trusty
os:
- linux
- osx
addons:
  homebrew:
    packages:
      - autoconf
      - automake
      - gnutls
      - texinfo
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  global:
  - EMAKE_SHA1=5936c6cfd7e9f2aa94ae6a49f614e22c15dc449f
  - EMACS_DIR=$HOME/emacs
  - EMACS=$HOME/emacs/src/emacs
  matrix:
  - EMACS_VERSION=26.3
  - EMACS_VERSION=snapshot
before_install:
- make setup
- wget "https://raw.githubusercontent.com/vermiculus/emake.el/${EMAKE_SHA1}/emake.mk"
install:
- make install
script:
- time make travis-script
